---
ratio: [1 ,1]
image_width: 200
samples_per_pixel: 1
max_depth: 1
scene: "cornell_box"

camera:
  viewport_height: 2.0
  focal_length: 1.0
  look_at: [278,   278,      0]
  origin:  [278.0, 278.0, -800]



